permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: CJ Xu
  email: 14xuchenjian@tongji.edu.cn
  link: http://fire-emblem.github.com
  weibo: http://weibo.com/273121133
  github: http://github.com/fire-emblem
  music: 
  linkedin: 

# 站点信息
title: 徐晨剑的博客
description: My personal blog
url: http://fire-emblem.github.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: http://fire-emblem.github.com

# disqus 设置
disqus:
  shortname: fire-emblem

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档